/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD_PF_11_Octobre;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Paire a= new Paire (1,2);
       System.out.println( a.toString());
        
    }
}
